### ISSUE TITLE
Failed to fetch object, underlying error: #<HTTPClient::ConnectTimeoutError: execution expired>

### ISSUE THREAD

**Issue by ldrmcml** [yudai/cf_nise_installer#118] opened 2014-10-20 02:50 UTC
#[6945] INFO: Installing package buildpack_go
#[6945] INFO: Running the packaging script for buildpack_go
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:163:in `rescue in find_in_indices': Blobstore error: Failed to fetch object, underlying error: #<HTTPClient::ConnectTimeoutError: execution expired> /root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:775:in `initialize' (Bosh::Cli::BlobstoreError)
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:775:in `new'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:775:in `create_socket'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:732:in `block in connect'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:731:in `connect'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:594:in `query'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:161:in `query'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:1060:in `do_get_block'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:869:in `block in do_request'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:956:in `protect_keep_alive_disconnected'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:868:in `do_request'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:756:in `request'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:661:in `get'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/simple_blobstore_client.rb:38:in `get_file'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/s3_blobstore_client.rb:87:in `get_file'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/base.rb:50:in `get'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_common-1.2175.0/lib/common/retryable.rb:21:in `block in retryer'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_common-1.2175.0/lib/common/retryable.rb:19:in `loop'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_common-1.2175.0/lib/common/retryable.rb:19:in `retryer'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:150:in `find_in_indices'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:109:in `find_package'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:306:in `find_package_archive'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/bosh.rb:251:in `get_source_package'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_agent-1.2175.0/lib/bosh_agent/message/compile_package.rb:62:in `start'
/root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_agent-1.2175.0/lib/bosh_agent/message/compile_package.rb:31:in `process'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:218:in `run_packaging'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:208:in `install_package'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:194:in `block in install_packages'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:192:in `each'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:192:in `install_packages'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:265:in `install_job'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:107:in `run_default_mode'
/home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:70:in `run'
./bin/nise-bosh:4:in `<main>'
	from /root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:121:in `find_in_indices'
	from /root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:109:in `find_package'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:306:in `find_package_archive'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/bosh.rb:251:in `get_source_package'
	from /root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_agent-1.2175.0/lib/bosh_agent/message/compile_package.rb:62:in `start'
	from /root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_agent-1.2175.0/lib/bosh_agent/message/compile_package.rb:31:in `process'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:218:in `run_packaging'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:208:in `install_package'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:194:in `block in install_packages'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:192:in `each'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:192:in `install_packages'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:265:in `install_job'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:107:in `run_default_mode'
	from /home/cf/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:70:in `run'
	from ./bin/nise-bosh:4:in `<main>'
root@ubuntu:/home/cf#

**Comment by jeffkit** [comment] 2015-03-12 03:26
Got the same issue too.

**Comment by guodfnet** [comment] 2015-03-16 07:34
我也遇见了，完全是网络问题，及时你的浏览器可以访问的网站，ruby脚本不一定可以访问这个网站，因为这里面的很多文件都是通过ruby脚本来下载的

**Comment by yudai** [comment] 2015-03-16 17:15
I assume that the root cause of the error is a network problem.
When you encountered this error, I think you can solve the problem by just rerunning the script.
You can also `cd` into the directory and run `bosh create release --force` command to create a dev release. Rerun this command until it completes when it fails during the process. when there is a dev release existing, the installer uses the files ins the release and do not download anything from the internet during the process. This would be useful to ensure the installer work without network errors.
You can delete the `cf-release` directory to clean up all cached files when the problem persists.

**Comment by yudai** [comment] 2015-08-24 21:20
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.

**Closed by yudai** 2015-08-24 21:20 UTC
